# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool: Default

jobs:
- job: job1
  steps:
  - script: |
      echo Hello, world!
- job: job2
  steps:
  - script: |
      echo Hello world2
- job: job3
  steps:
  - script: |
      echo Hello world3